FolinusBaseBundle:
    resource: "@FolinusBaseBundle/Resources/config/routing.xml"
    prefix:   /

FolinusBlogBundle:
    resource: "@FolinusBlogBundle/Resources/config/routing.xml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
